In [1]:
import numpy as np

In [2]:
a = np.array([2, 4, 6, 8])
a

array([2, 4, 6, 8])

In [3]:
s = np.array([[1, 3], [2, 4]])
s

array([[1, 3],
       [2, 4]])

In [4]:
d = np.array( 
    [ 
    [ [1, 3], [2, 4] ],
    [ [5, 7], [6, 8] ]
    ]
    )
d 

array([[[1, 3],
        [2, 4]],

       [[5, 7],
        [6, 8]]])

In [5]:
e = np.array([[1, 2, 3, 4], [5, 6, 7, 8], 2, 4, 'bhoot'])
e

<ipython-input-5-7b0eb5e97c31>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  e = np.array([[1, 2, 3, 4], [5, 6, 7, 8], 2, 4, 'bhoot'])


array([list([1, 2, 3, 4]), list([5, 6, 7, 8]), 2, 4, 'bhoot'],
      dtype=object)

In [6]:
e.dtype

dtype('O')

In [7]:
w = np.array(['b', 'h', 'o', 'o', 't'])
w


array(['b', 'h', 'o', 'o', 't'], dtype='<U1')

In [8]:
name_list = ['kushang', 'bhoot', 'pisaj', 'chincho chu cha']

name_array = np.array(name_list)

name_array

array(['kushang', 'bhoot', 'pisaj', 'chincho chu cha'], dtype='<U15')

In [20]:
# write the python program to verify if the givin input is armstrong number or not.

p = 0

num = input("enter numbere here: ")

a = [int(i) for i in num]

for j in range(len(a)):
  p = p + a[j]**len(a)

if p == int(num):
  print("This is the armstrong number.")
else:
  print("This is not a armstrong number.")

enter numbere here: 371
This is the armstrong number.


In [22]:
# to check if certain givin number is greater than all the given number

num = eval(input("enter the list of number"))
n = int(input("enter a single number: "))

print(all(x>n for x in num))

enter the list of number2, 3, 4, 5
enter a single number: 1
True


In [39]:
num = eval(input())
a = int(input())
print(a)

SyntaxError: ignored